# Generated by Django 3.2.3 on 2022-03-28 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_name', models.CharField(max_length=20)),
                ('main_subject', models.CharField(max_length=20)),
                ('experience', models.IntegerField()),
            ],
        ),
    ]
