# Generated by Django 3.2.3 on 2022-03-28 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('course', models.CharField(max_length=15)),
                ('year', models.CharField(max_length=10)),
                ('marks', models.FloatField()),
            ],
        ),
    ]
