# Generated by Django 3.2.3 on 2022-03-28 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentAwards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('award', models.CharField(max_length=20)),
                ('student_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stdent_details', to='student.studentdetail')),
            ],
        ),
    ]
